### ISSUE TITLE
Assignment 1 feedback.

### ISSUE THREAD

**Issue by tombroomfield** [johnnyweb1/homework-portfolio#2]
Hi John,
Fantastic assignment. Really great use of folders to keep your project clean. Great understanding of the core concepts we have learnt so far. Great creativity on the site and the mailto is a clever addition. My only feedback is around the consistency of your indentation in both your html and css, but that's a fairly minor nitpick at this point. Fantastic start to the course!

**Comment by johnnyweb1** [comment]
Thanks Tom. Im putting more effort into keeping code correctly indented for next time. Thanks for the positive feedback.
